spring:
  profiles:
    active: #spring.profiles.active#

  server:
    port: 8080
    servlet:
      context-path: /
      encoding:
        charset: UTF-8
        enabled: true
        force:  true

  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
      
  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        
      

